[LIGO-487] Set up LIGO backend prototype
serokell/ligo-webide pull request #5
Opened 2022-04-20 04:19 UTC by pgujjula

Problem: We need a backend service to compile LIGO contracts.

Solution: Create a backend server prototype using servant, that can take
a ligo contract, compile it, and return the compiled result, or the
error message in case of invalid code. Also add a unit test.

[//]: # (This is a template of a pull request template.)
[//]: # (You should modify it considering specifics of a particular repository and put it there.)
[//]: # (Comments like this are meta-comments, they shouldn't be present in the final template.)
[//]: # (Comments starting with '

[//]: # (Here you can add a link to the corresponding issue tracker, e. g. https://issues.serokell.io/issue/AD-)
[//]: # (For GitHub/GitLab issues it is better to use just hash symbol or exclamation mark as it is more resistant to repo movements)
[//]: # (In this case please also prefix the link with "Resolves" keyword)
[//]: # (See https://docs.gitlab.com/ee/user/project/issues/managing_issues.html#closing-issues-automatically)
[//]: # (See https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords)
## Related issue(s)

## :white_check_mark: Checklist for your Pull Request

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

[//]: # (Add more docs here if you have them in the repository)
- Documentation
  - [ ] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

[//]: # (Mostly for public repositories)
[//]: # (Recording changes is optional, depends on repository, useful for some libs)
- Public contracts
  - [ ] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [ ] I added an entry to the [changelog](../tree/master/CHANGES.md) if my changes are visible to the users
        and
  - [ ] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

[//]: # (Update link to style guide if necesary or remove if it's not present)

- [ ] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [ ] My code complies with the [style guide](../tree/master/docs/code-style.md).

2022-04-27 12:58 UTC, sashasashasasha151 requested changes

2022-04-27 12:58 UTC, sashasashasasha151 commented on ligo-webide-backend/src/Lib.hs
> +type API = "compile" :> ReqBody '[JSON] Text :> Post '[JSON] Text
What about multiple file contracts? How it works in ligo?

2022-04-27 12:58 UTC, sashasashasasha151 commented on ligo-webide-backend/src/Lib.hs
> +compile source = withSystemTempFile "input.mligo" $ \fp handle -> do
Will other file extensions also work?

2022-06-16 06:55 UTC, pgujjula commented
Closing this because https://github.com/serokell/ligo-webide/pull/14 contains these changes.

2022-06-16 06:55 UTC, closed without merging